#!/bin/bash
#update snps position in plink files
#initiation labels
id=$1
pos_db=/home/mrog/data/ucsc
#check input
[ -z $id ] && { echo "missing id"; exit 1; }
#i=chr
i=1
#subset rs by chromosome from bim file
awk -v i=$i '{ if($1 == i) {print $2}}' $id.bim > tmp.chr$i 
#intersect two lists of rs
[ -f "$id.chr$i.snps" ] && rm $id.chr$i.snps
while read rs1; do
	while read line; do
		read -r -a array <<< "$line"
		rs2=${array[2]}
		pos=${array[1]}
		if [ "$rs1" == "$rs2" ]; then 
		       echo -e "$rs2\t$pos" >> $id.chr$i.snps
		       break
		fi
	done < $pos_db/chr$i.txt	
done < tmp.chr$i
